[features]
seeds = false
skip-lint = false
[programs.localnet]
vault_program = "3PHnbmYZU1zVmD3rrLbkFTQonrRFj2GwRZwnLHJunAfL"

[programs.devnet]
vault_program = "3PHnbmYZU1zVmD3rrLbkFTQonrRFj2GwRZwnLHJunAfL"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/Users/orion/Documents/GitHub/vault-program/vault_upgrade_authority"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
