/**
 * This code was GENERATED using the solita package.
 * Please DO NOT EDIT THIS FILE, instead rerun solita to update it or write a wrapper to add functionality.
 *
 * See: https://github.com/metaplex-foundation/solita
 */

import * as splToken from '@solana/spl-token'
import * as beet from '@metaplex-foundation/beet'
import * as web3 from '@solana/web3.js'

/**
 * @category Instructions
 * @category FreezeNonFungibel
 * @category generated
 */
export const freezeNonFungibelStruct = new beet.BeetArgsStruct<{
  instructionDiscriminator: number[] /* size: 8 */
}>(
  [['instructionDiscriminator', beet.uniformFixedSizeArray(beet.u8, 8)]],
  'FreezeNonFungibelInstructionArgs'
)
/**
 * Accounts required by the _freezeNonFungibel_ instruction
 *
 * @property [_writable_] tokenAccount
 * @property [] tokenMint
 * @property [] tokenMintEdition
 * @property [_writable_, **signer**] signer
 * @property [] delegate
 * @property [] tokenMetadataProgram
 * @category Instructions
 * @category FreezeNonFungibel
 * @category generated
 */
export type FreezeNonFungibelInstructionAccounts = {
  tokenAccount: web3.PublicKey
  tokenMint: web3.PublicKey
  tokenMintEdition: web3.PublicKey
  signer: web3.PublicKey
  delegate: web3.PublicKey
  tokenProgram?: web3.PublicKey
  tokenMetadataProgram: web3.PublicKey
  anchorRemainingAccounts?: web3.AccountMeta[]
}

export const freezeNonFungibelInstructionDiscriminator = [
  233, 196, 185, 246, 112, 72, 41, 94,
]

/**
 * Creates a _FreezeNonFungibel_ instruction.
 *
 * @param accounts that will be accessed while the instruction is processed
 * @category Instructions
 * @category FreezeNonFungibel
 * @category generated
 */
export function createFreezeNonFungibelInstruction(
  accounts: FreezeNonFungibelInstructionAccounts,
  programId = new web3.PublicKey('undefined')
) {
  const [data] = freezeNonFungibelStruct.serialize({
    instructionDiscriminator: freezeNonFungibelInstructionDiscriminator,
  })
  const keys: web3.AccountMeta[] = [
    {
      pubkey: accounts.tokenAccount,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: accounts.tokenMint,
      isWritable: false,
      isSigner: false,
    },
    {
      pubkey: accounts.tokenMintEdition,
      isWritable: false,
      isSigner: false,
    },
    {
      pubkey: accounts.signer,
      isWritable: true,
      isSigner: true,
    },
    {
      pubkey: accounts.delegate,
      isWritable: false,
      isSigner: false,
    },
    {
      pubkey: accounts.tokenProgram ?? splToken.TOKEN_PROGRAM_ID,
      isWritable: false,
      isSigner: false,
    },
    {
      pubkey: accounts.tokenMetadataProgram,
      isWritable: false,
      isSigner: false,
    },
  ]

  if (accounts.anchorRemainingAccounts != null) {
    for (const acc of accounts.anchorRemainingAccounts) {
      keys.push(acc)
    }
  }

  const ix = new web3.TransactionInstruction({
    programId,
    keys,
    data,
  })
  return ix
}
