/**
 * This code was GENERATED using the solita package.
 * Please DO NOT EDIT THIS FILE, instead rerun solita to update it or write a wrapper to add functionality.
 *
 * See: https://github.com/metaplex-foundation/solita
 */

import * as beet from '@metaplex-foundation/beet'
import * as web3 from '@solana/web3.js'

/**
 * @category Instructions
 * @category InitTestVault
 * @category generated
 */
export const initTestVaultStruct = new beet.BeetArgsStruct<{
  instructionDiscriminator: number[] /* size: 8 */
}>(
  [['instructionDiscriminator', beet.uniformFixedSizeArray(beet.u8, 8)]],
  'InitTestVaultInstructionArgs'
)
/**
 * Accounts required by the _initTestVault_ instruction
 *
 * @property [_writable_] testVault
 * @property [_writable_, **signer**] signer
 * @category Instructions
 * @category InitTestVault
 * @category generated
 */
export type InitTestVaultInstructionAccounts = {
  testVault: web3.PublicKey
  signer: web3.PublicKey
  systemProgram?: web3.PublicKey
  anchorRemainingAccounts?: web3.AccountMeta[]
}

export const initTestVaultInstructionDiscriminator = [
  201, 105, 137, 157, 100, 49, 82, 89,
]

/**
 * Creates a _InitTestVault_ instruction.
 *
 * @param accounts that will be accessed while the instruction is processed
 * @category Instructions
 * @category InitTestVault
 * @category generated
 */
export function createInitTestVaultInstruction(
  accounts: InitTestVaultInstructionAccounts,
  programId = new web3.PublicKey('undefined')
) {
  const [data] = initTestVaultStruct.serialize({
    instructionDiscriminator: initTestVaultInstructionDiscriminator,
  })
  const keys: web3.AccountMeta[] = [
    {
      pubkey: accounts.testVault,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: accounts.signer,
      isWritable: true,
      isSigner: true,
    },
    {
      pubkey: accounts.systemProgram ?? web3.SystemProgram.programId,
      isWritable: false,
      isSigner: false,
    },
  ]

  if (accounts.anchorRemainingAccounts != null) {
    for (const acc of accounts.anchorRemainingAccounts) {
      keys.push(acc)
    }
  }

  const ix = new web3.TransactionInstruction({
    programId,
    keys,
    data,
  })
  return ix
}
